Repository HatchGameEngine/HatchGameEngine, pull requests merged in 2025-05, with the labels that each got.

#27 LoadMusicResource: Remove duplicate ResourceStream
  source/Engine/Scene.cpp
Labels: optimization, scripting

#31 Fixup SoftwareRenderer Parallax + memory leak fixes
  source/Engine/Application.cpp
  source/Engine/Bytecode/ScriptManager.cpp
  source/Engine/Diagnostics/Log.cpp
  source/Engine/InputManager.cpp
  source/Engine/Rendering/Software/SoftwareRenderer.cpp
Labels: bug

#29 Implement game:// URL
  include/Engine/Filesystem/File.h
  include/Engine/Filesystem/Path.h
  include/Engine/IO/FileStream.h
  include/Engine/ResourceTypes/ResourceManager.h
  source/Engine/Bytecode/SourceFileMap.cpp
  source/Engine/Bytecode/StandardLibrary.cpp
  source/Engine/Filesystem/File.cpp
  source/Engine/Filesystem/Path.cpp
  source/Engine/Filesystem/VFS/VirtualFileSystem.cpp
  source/Engine/IO/FileStream.cpp
  source/Engine/ResourceTypes/ResourceManager.cpp
Labels: enhancement, refactoring

#26 New StandardLibrary Functionality
  include/Engine/Bytecode/ScriptEntity.h
  include/Engine/Math/Math.h
  include/Engine/Types/Entity.h
  source/Engine/Application.cpp
  source/Engine/Bytecode/ScriptEntity.cpp
  source/Engine/Bytecode/ScriptManager.cpp
  source/Engine/Bytecode/StandardLibrary.cpp
  source/Engine/Math/Math.cpp
  source/Engine/Types/Entity.cpp
  source/Engine/Types/EntityTypes.h
Labels: enhancement, scripting

#41 Move some Scene functions to Collision class
  guides/Documentation.htm
  source/Engine/Bytecode/StandardLibrary.cpp
Labels: scripting

#38 Implement separate opcode for super invocations
  include/Engine/Bytecode/Compiler.h
  include/Engine/Bytecode/VMThread.h
  source/Engine/Bytecode/Bytecode.cpp
  source/Engine/Bytecode/Compiler.cpp
  source/Engine/Bytecode/Types.cpp
  source/Engine/Bytecode/Types.h
  source/Engine/Bytecode/VMThread.cpp
Labels: bug, optimization, scripting, refactoring

#37 Throw error when trying to use a class that hasn't been loaded as a superclass
  include/Engine/Bytecode/ScriptManager.h
  source/Engine/Bytecode/ScriptManager.cpp
  source/Engine/Bytecode/Types.cpp
  source/Engine/Bytecode/Types.h
  source/Engine/Bytecode/VMThread.cpp
Labels: scripting

#36 Values and PrintBuffer refactor
  Makefile
  VisualC/HatchGameEngine.vcxproj
  VisualC/HatchGameEngine.vcxproj.filters
  guides/Documentation.htm
  include/Engine/Bytecode/ScriptManager.h
  include/Engine/Bytecode/VMThread.h
  include/Engine/Bytecode/Value.h
  include/Engine/Bytecode/ValuePrinter.h
  include/Engine/Bytecode/Values.h
  include/Engine/Utilities/PrintBuffer.h
  source/Engine/Bytecode/Compiler.cpp
  source/Engine/Bytecode/ScriptManager.cpp
  source/Engine/Bytecode/StandardLibrary.cpp
  source/Engine/Bytecode/Types.cpp
  source/Engine/Bytecode/VMThread.cpp
  source/Engine/Bytecode/Value.cpp
  source/Engine/Bytecode/ValuePrinter.cpp
  source/Engine/Bytecode/Values.cpp
  source/Engine/Utilities/PrintBuffer.cpp
Labels: bug, documentation, enhancement, scripting, refactoring
