Repository HatchGameEngine/HatchGameEngine, pull requests merged in 2025-01, with the labels that each got.

#5 Optimize OpenGL Renderer
  source/Engine/Application.cpp
  source/Engine/Rendering/GL/GLRenderer.cpp
  source/Engine/Rendering/GL/GLShader.cpp
Labels: optimization, rendering

#7 Optimizations: Implement const keyword
  include/Engine/Bytecode/Compiler.h
  include/Engine/Bytecode/VMThread.h
  source/Engine/Bytecode/Bytecode.cpp
  source/Engine/Bytecode/Compiler.cpp
  source/Engine/Bytecode/CompilerEnums.h
  source/Engine/Bytecode/Types.h
  source/Engine/Bytecode/VMThread.cpp
  source/Engine/Scene.cpp
Labels: enhancement, optimization, scripting, refactoring

#8 Misc memory management improvements
  source/Engine/Application.cpp
  source/Engine/Bytecode/StandardLibrary.cpp
  source/Engine/Diagnostics/Memory.cpp
  source/Engine/Scene.cpp
Labels: optimization

#6 Function-pointer based VM runtime
  CMakeLists.txt
  include/Engine/Bytecode/VMThread.h
  source/Engine/Bytecode/Bytecode.cpp
  source/Engine/Bytecode/Compiler.cpp
  source/Engine/Bytecode/ScriptManager.cpp
  source/Engine/Bytecode/Types.cpp
  source/Engine/Bytecode/Types.h
  source/Engine/Bytecode/VMThread.cpp
Labels: optimization, scripting, refactoring

#9 GL: Potentially fix crash and optimize some more
  include/Engine/Rendering/GL/GLShader.h
  source/Engine/Rendering/GL/GLRenderer.cpp
  source/Engine/Rendering/GL/GLShader.cpp
Labels: bug, optimization, rendering, refactoring

#11 Misc memory leaks & undefined behavior bugfixes
  include/Engine/Rendering/GameTexture.h
  include/Engine/Types/Entity.h
  source/Engine/Bytecode/StandardLibrary.cpp
  source/Engine/Rendering/GL/GLRenderer.cpp
  source/Engine/ResourceTypes/SceneFormats/RSDKSceneReader.cpp
  source/Engine/Scene/SceneInfo.cpp
  source/Engine/TextFormats/XML/XMLParser.cpp
Labels: bug

#12 Linux: Fix glewInit failing on Wayland
  source/Engine/Rendering/GL/GLRenderer.cpp
Labels: bug
